import Head from "next/head";
import { api } from "~/utils/api";
import Input from "~/components/Input";
import { useState } from "react";

export default function Home() {
  const post = api.postApi.postSample.useMutation();

  const [inputs, setInputs] = useState({ name: "", email: "", age: "" });
  const getInputData = (event: React.ChangeEvent<HTMLInputElement>) => {
    let { name, value } = event.target;
    let u = { [name]: value };
    setInputs((prev) => ({ ...prev, ...u }));
  };
  const sendInput = () => {
    post.mutate(inputs);
  };
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <Input
          type="text"
          placeholder="Enter your name"
          onChange={getInputData}
          name="name"
        />
        <Input
          type="email"
          placeholder="Enter your email"
          onChange={getInputData}
          name="email"
        />
        <Input
          type="number"
          placeholder="Enter your age"
          onChange={getInputData}
          name="age"
        />
        <button className="btn btn-primary mt-3" onClick={sendInput}>
          Add Data
        </button>
      </main>
    </>
  );
}
