import Head from "next/head";
import { api } from "~/utils/api";
import Input from "~/components/Input";

export default function Home() {
  const hello = api.post.hello.useQuery({ text: "from tRPC" });

  const getInputData = (event: React.ChangeEvent<HTMLInputElement>) => {
    let{name, value} = event.target
    let u = {[name]: value}
  };

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <Input
          type="text"
          placeholder="Enter your name"
          onChange={getInputData}
          name="name"
        />
        <Input
          type="email"
          placeholder="Enter your email"
          onChange={getInputData}
          name="email"
        />
        <Input
          type="number"
          placeholder="Enter your age"
          onChange={getInputData}
          name="age"
        />
        <button className="btn btn-primary mt-3">Add Data</button>
      </main>
    </>
  );
}
